### ISSUE TITLE
CSS alignment problems

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-repl#28]
There are a couple of places where some small margin/padding corrections would be nice.

1. dropdown component
2. error message showing number of errors

![Screenshot 2019-10-11 at 09 27 36](https://user-images.githubusercontent.com/9945366/66629111-8151e700-ec09-11e9-8be1-89561f951ae5.png)
![Screenshot 2019-10-11 at 09 27 45](https://user-images.githubusercontent.com/9945366/66629112-81ea7d80-ec09-11e9-9ac3-ebcf50bdec5f.png)

**Comment by alexandriaroberts** [comment]
Hey Alex, I would like to do this! :)
