### ISSUE TITLE
Update repl to use the latest version of generators

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-repl#52]
We added support for raw-nodes in the latest release. So, lets update the repl.

**Comment by alexnm** [comment]
I did that a few days ago when the packages were published

**Comment by JayaKrishnaNamburu** [comment]
Ahh 😅 ok, i was using this deployment URL --> https://github.com/teleporthq/teleport-repl/pull/48 and thought it's not updated yet 😁
